import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/api.dart';
import '../../core/models.dart';
import '../../core/theme.dart';
class AiAgentScreen extends ConsumerStatefulWidget{const AiAgentScreen({super.key});@override ConsumerState<AiAgentScreen> createState()=>_AiAgentScreenState();}
class _AiAgentScreenState extends ConsumerState<AiAgentScreen>{final p=TextEditingController();final List<String> log=[];List<ChatAction> actions=[];bool loading=false;
Future<void> ask()async{final text=p.text.trim();if(text.isEmpty)return;setState(()=>loading=true);try{final data=ApiClient.decode(await ApiClient.post('/ai/chat',{'prompt':text,'mode':'editor'})) as Map;final r=ChatResponse.fromJson(Map<String,dynamic>.from(data));setState((){log.add(r.response);actions=r.actions;});}catch(e){setState(()=>log.add('$e'));}finally{setState(()=>loading=false);}}
Future<void> apply(ChatAction a)async{try{final d=ApiClient.decode(await ApiClient.post('/ai/agent/execute',{'action':a.type,'path':a.path,'content':a.content,'command':a.command})) as Map;setState(()=>log.add('${d['response'] ?? 'Acción aplicada'}'));}catch(e){setState(()=>log.add('$e'));}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Numination AI Agent')),body:Column(children:[Expanded(child:ListView(padding:const EdgeInsets.all(16),children:[...log.map((x)=>Padding(padding:const EdgeInsets.only(bottom:10),child:GlassCard(child:SelectableText(x)))),if(actions.isNotEmpty)GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Acciones propuestas',style:TextStyle(fontWeight:FontWeight.w800,color:AppColors.yellow)),const SizedBox(height:10),...actions.map((a)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(a.description),subtitle:Text('${a.type}${a.path==null?'':' · ${a.path}'}',style:const TextStyle(color:AppColors.muted)),trailing:FilledButton(onPressed:()=>apply(a),child:const Text('Aplicar'))))]))])),if(loading)const LinearProgressIndicator(),SafeArea(child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:TextField(controller:p,onSubmitted:(_)=>ask(),decoration:const InputDecoration(hintText:'Describe el cambio…'))),const SizedBox(width:8),IconButton.filled(onPressed:loading?null:ask,icon:const Icon(Icons.auto_awesome))])))]));
}
