import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/api.dart';
import '../../core/auth_controller.dart';
import '../../core/models.dart';
import '../../core/theme.dart';

class ChatScreen extends ConsumerStatefulWidget{const ChatScreen({super.key});@override ConsumerState<ChatScreen> createState()=>_ChatScreenState();}
class _ChatScreenState extends ConsumerState<ChatScreen>{final prompt=TextEditingController();final scroll=ScrollController();final List<(String,String)> messages=[];bool loading=false;String mode='chat';
  Future<void> send()async{final text=prompt.text.trim();if(text.isEmpty||loading)return;prompt.clear();setState((){messages.add(('Tú',text));loading=true;});try{final data=ApiClient.decode(await ApiClient.post('/ai/chat',{'prompt':text,'mode':mode})) as Map;final r=ChatResponse.fromJson(Map<String,dynamic>.from(data));setState(()=>messages.add(('Numination',r.response)));}catch(e){setState(()=>messages.add(('Error','$e')));}finally{setState(()=>loading=false);}}
  @override void dispose(){prompt.dispose();scroll.dispose();super.dispose();}
  @override Widget build(BuildContext context){final auth=ref.watch(authControllerProvider);final credits=auth is AuthAuthenticated?auth.user.balance:0;return Scaffold(appBar:AppBar(title:const Text('AI Chat'),actions:[Padding(padding:const EdgeInsets.symmetric(horizontal:14),child:Center(child:Text('$credits créditos',style:const TextStyle(color:AppColors.yellow,fontSize:12,fontWeight:FontWeight.w700))))]),body:Column(children:[SingleChildScrollView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.all(12),child:Row(children:['chat','planificador','editor','terminal'].map((m)=>Padding(padding:const EdgeInsets.only(right:8),child:ChoiceChip(label:Text(m),selected:mode==m,onSelected:(_)=>setState(()=>mode=m))).toList())),Expanded(child:messages.isEmpty?const Center(child:Text('Pregunta a Numination AI…',style:TextStyle(color:AppColors.muted))):ListView.builder(controller:scroll,padding:const EdgeInsets.all(16),itemCount:messages.length,itemBuilder:(c,i){final m=messages[i];final mine=m.$1=='Tú';return GlassCard(padding:const EdgeInsets.all(14),onTap:null,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(m.$1,style:TextStyle(color:mine?AppColors.cyan:AppColors.yellow,fontWeight:FontWeight.w800)),const SizedBox(height:7),SelectableText(m.$2,style:const TextStyle(height:1.45)),]));})),if(loading)const LinearProgressIndicator(),SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(12,8,12,12),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[Expanded(child:TextField(controller:prompt,minLines:1,maxLines:5,onSubmitted:(_)=>send(),decoration:const InputDecoration(hintText:'Pregunta a Numination AI…'))),const SizedBox(width:8),IconButton.filled(onPressed:loading?null:send,icon:const Icon(Icons.send))])))]));}
}
