import 'package:flutter/material.dart';
import '../../core/api.dart';
import '../../core/models.dart';
import '../../core/theme.dart';
class CreditsScreen extends StatefulWidget{const CreditsScreen({super.key});@override State<CreditsScreen> createState()=>_CreditsScreenState();}
class _CreditsScreenState extends State<CreditsScreen>{Map<String,dynamic>? overview;List<CreditLog> history=[];bool loading=true;
Future<void> load()async{setState(()=>loading=true);try{final o=ApiClient.decode(await ApiClient.get('/credits')) as Map;final h=ApiClient.decode(await ApiClient.get('/credits/history')) as Map;setState((){overview=Map<String,dynamic>.from(o);history=((h['logs'] as List?)??const[]).map((e)=>CreditLog.fromJson(Map<String,dynamic>.from(e))).toList();});}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}finally{if(mounted)setState(()=>loading=false);}}
Future<void> recharge(BillingPlan p)async{try{final d=ApiClient.decode(await ApiClient.post('/credits/recharge',{'packageId':p.id})) as Map;if(mounted)showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Solicitud creada'),content:SelectableText('${d['message']}\n\nReferencia: ${d['referenceCode']}\nCréditos: ${d['credits']}\n${d['paypalUrl'] ?? ''}'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cerrar'))]));await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}
@override void initState(){super.initState();load();}
@override Widget build(BuildContext context){final plans=((overview?['plans'] as List?)??const[]).map((e)=>BillingPlan.fromJson(Map<String,dynamic>.from(e))).toList();final bal=overview?['balance']??0;return Scaffold(appBar:AppBar(title:const Text('Créditos')),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(18),children:[GlassCard(child:Row(children:[const Icon(Icons.bolt,size:40,color:AppColors.yellow),const SizedBox(width:14),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Saldo',style:TextStyle(color:AppColors.muted)),Text('$bal',style:const TextStyle(fontSize:32,fontWeight:FontWeight.w900)),Text('${overview?['tier']??'FREE'}',style:const TextStyle(color:AppColors.cyan,fontWeight:FontWeight.w700))])])),const SizedBox(height:20),const Text('Comprar créditos / plan',style:TextStyle(fontSize:19,fontWeight:FontWeight.w800)),const SizedBox(height:10),if(loading)const LinearProgressIndicator(),...plans.map((p)=>Padding(padding:const EdgeInsets.only(bottom:10),child:GlassCard(child:ListTile(contentPadding:EdgeInsets.zero,title:Text(p.title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${p.credits} créditos · ${p.priceLabel}',style:const TextStyle(color:AppColors.muted)),trailing:FilledButton(onPressed:()=>recharge(p),child:const Text('Solicitar'))))),const SizedBox(height:14),const Text('Historial',style:TextStyle(fontSize:19,fontWeight:FontWeight.w800)),const SizedBox(height:8),...history.map((l)=>ListTile(contentPadding:EdgeInsets.zero,leading:Icon(l.amount>=0?Icons.add_circle_outline:Icons.remove_circle_outline,color:l.amount>=0?AppColors.green:AppColors.red),title:Text(l.reason),subtitle:Text(l.timestamp,style:const TextStyle(color:AppColors.muted)),trailing:Text('${l.amount>=0?'+':''}${l.amount}',style:TextStyle(color:l.amount>=0?AppColors.green:AppColors.red,fontWeight:FontWeight.w800))))])));}
}
