import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/auth_controller.dart';
import '../../core/models.dart';
import '../../core/theme.dart';
import '../controllers.dart';
import 'workspace_screen.dart';
import 'chat_screen.dart';
import 'credits_screen.dart';
import 'memory_screen.dart';
import 'notifications_screen.dart';
import 'profile_screen.dart';
import 'settings_screen.dart';
import 'owner_screen.dart';

class HomeScreen extends ConsumerStatefulWidget { const HomeScreen({super.key}); @override ConsumerState<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends ConsumerState<HomeScreen>{
  int index=0;
  final pages = const [DashboardTab(), WorkspaceScreen(), ChatScreen(), MemoryScreen(), CreditsScreen()];
  @override Widget build(BuildContext context){
    final auth=ref.watch(authControllerProvider); final user=auth is AuthAuthenticated?auth.user:null;
    return Scaffold(
      appBar: AppBar(title: const Text('Numination',style:TextStyle(fontWeight:FontWeight.w800)),actions:[IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const NotificationsScreen())),icon:const Icon(Icons.notifications_none)),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ProfileScreen(user:user))),icon:const Icon(Icons.account_circle_outlined))]),
      drawer: Drawer(backgroundColor:AppColors.sidebar,child:SafeArea(child:Column(children:[ListTile(leading:const Icon(Icons.auto_awesome,color:AppColors.cyan),title:const Text('Numination',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:const Text('AI development workspace',style:TextStyle(color:AppColors.muted))),const Divider(color:AppColors.border),_Nav('Projects',Icons.folder_outlined,0,index,()=>setState(()=>index=0)),_Nav('Workspace',Icons.code,1,index,()=>setState(()=>index=1)),_Nav('AI Chat',Icons.auto_awesome,2,index,()=>setState(()=>index=2)),_Nav('Memory',Icons.psychology_outlined,3,index,()=>setState(()=>index=3)),_Nav('Credits',Icons.bolt_outlined,4,index,()=>setState(()=>index=4)),ListTile(leading:const Icon(Icons.settings_outlined),title:const Text('Settings'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const SettingsScreen()))),if(user?.role.toUpperCase()=='OWNER')ListTile(leading:const Icon(Icons.admin_panel_settings_outlined),title:const Text('Owner console'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const OwnerScreen()))),const Spacer(),if(user!=null)ListTile(leading:CircleAvatar(child:Text(user.email.isNotEmpty?user.email[0].toUpperCase():'N')),title:Text(user.email.split('@').first),subtitle:Text('${user.tier} · ${user.balance} créditos',style:const TextStyle(color:AppColors.muted)))]))),
      body: IndexedStack(index:index,children:pages),
    );
  }
}
class _Nav extends StatelessWidget{final String label;final IconData icon;final int item;final int selected;final VoidCallback onTap;const _Nav(this.label,this.icon,this.item,this.selected,this.onTap);@override Widget build(BuildContext c)=>ListTile(selected:item==selected,selectedTileColor:AppColors.cyan.withValues(alpha:.11),leading:Icon(icon,color:item==selected?AppColors.cyan:AppColors.muted),title:Text(label),onTap:(){Navigator.pop(c);onTap();});}

class DashboardTab extends ConsumerWidget{const DashboardTab({super.key});@override Widget build(BuildContext context,WidgetRef ref){final projects=ref.watch(projectsProvider);return RefreshIndicator(onRefresh:()=>ref.read(projectsProvider.notifier).refresh(),child:ListView(padding:const EdgeInsets.all(18),children:[GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('¿Qué estás construyendo hoy?',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800)),const SizedBox(height:6),const Text('Tu workspace, memoria y asistente en un solo lugar.',style:TextStyle(color:AppColors.muted)),const SizedBox(height:16),Wrap(spacing:10,runSpacing:10,children:[FilledButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const WorkspaceScreen())),icon:const Icon(Icons.add),label:const Text('Nuevo proyecto')),OutlinedButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const ChatScreen())),icon:const Icon(Icons.auto_awesome),label:const Text('Preguntar a AI'))])])),const SizedBox(height:14),Row(children:[Expanded(child:GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Créditos',style:TextStyle(color:AppColors.muted)),Text(ref.watch(authControllerProvider) is AuthAuthenticated?(ref.watch(authControllerProvider) as AuthAuthenticated).user.balance.toString():'—',style:const TextStyle(fontSize:30,fontWeight:FontWeight.w800)),const Text('Plan actual',style:TextStyle(color:AppColors.cyan))]))),const SizedBox(width:12),const Expanded(child:GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Memoria',style:TextStyle(color:AppColors.muted)),const Text('Persistente',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800)),const Text('NUMINATION.md + recuerdos',style:TextStyle(color:AppColors.muted))])))]),const SizedBox(height:20),const Text('Proyectos recientes',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:10),projects.when(data:(items)=>items.isEmpty?const GlassCard(child:Column(children:[Icon(Icons.folder_open,size:42,color:AppColors.cyan),SizedBox(height:10),Text('Aún no tienes proyectos'),SizedBox(height:4),Text('Crea uno y Numination preparará su memoria inicial.',style:TextStyle(color:AppColors.muted))])):..._projectList(context, items),loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>GlassCard(child:Text('No se pudieron cargar proyectos: $e',style:const TextStyle(color:AppColors.red))) ])]);}
List<Widget> _projectList(BuildContext context, List<Project> items)=>items.take(8).map((p)=>Padding(padding:const EdgeInsets.only(bottom:10),child:GlassCard(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>WorkspaceScreen(initialProject:p))),child:Row(children:[Container(width:44,height:44,decoration:BoxDecoration(color:AppColors.cyan.withValues(alpha:.12),borderRadius:BorderRadius.circular(12)),child:const Icon(Icons.folder,color:AppColors.cyan)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p.name,style:const TextStyle(fontWeight:FontWeight.w800)),Text(p.description.isEmpty?'Proyecto Numination':p.description,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:AppColors.muted))]))]))).toList();}
