import 'package:flutter/material.dart';
import '../../core/api.dart';
import '../../core/models.dart';
import '../../core/theme.dart';
class MemoryScreen extends StatefulWidget{const MemoryScreen({super.key});@override State<MemoryScreen> createState()=>_MemoryScreenState();}
class _MemoryScreenState extends State<MemoryScreen>{List<MemoryItem> items=[];bool loading=true;Future<void> load()async{try{final d=ApiClient.decode(await ApiClient.get('/memory')) as Map;setState(()=>items=((d['memories'] as List?)??const[]).map((e)=>MemoryItem.fromJson(Map<String,dynamic>.from(e))).toList());}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}finally{if(mounted)setState(()=>loading=false);}}
Future<void> add()async{final t=TextEditingController();final c=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Guardar memoria'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:t,decoration:const InputDecoration(labelText:'Título')),const SizedBox(height:8),TextField(controller:c,minLines:3,maxLines:8,decoration:const InputDecoration(labelText:'Contenido'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Guardar'))]));if(ok==true){try{await ApiClient.post('/memory',{'title':t.text.trim(),'content':c.text.trim(),'type':'PROJECT'});await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}t.dispose();c.dispose();}
@override void initState(){super.initState();load();}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Memoria'),actions:[IconButton(onPressed:add,icon:const Icon(Icons.add))]),body:RefreshIndicator(onRefresh:load,child:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:items.isEmpty?[const GlassCard(child:Column(children:[Icon(Icons.psychology_outlined,size:44,color:AppColors.cyan),SizedBox(height:10),Text('No hay recuerdos todavía'),Text('Usa la memoria para conservar contexto entre sesiones.',style:TextStyle(color:AppColors.muted))]))]:items.map((m)=>Padding(padding:const EdgeInsets.only(bottom:10),child:GlassCard(child:ExpansionTile(tilePadding:EdgeInsets.zero,title:Text(m.title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(m.type,style:const TextStyle(color:AppColors.cyan,fontSize:11)),children:[Align(alignment:Alignment.centerLeft,child:SelectableText(m.content)),const SizedBox(height:10)]))).toList())));
}
