import 'package:flutter/material.dart';
import '../../core/api.dart';
import '../../core/theme.dart';
class OwnerScreen extends StatefulWidget{const OwnerScreen({super.key});@override State<OwnerScreen> createState()=>_OwnerScreenState();}
class _OwnerScreenState extends State<OwnerScreen>{Map<String,dynamic>?stats;List<Map<String,dynamic>>users=[],logs=[],pending=[];bool loading=true;String?error;
Future<void> load()async{setState(()=>loading=true);try{final results=await Future.wait([ApiClient.get('/owner?view=stats'),ApiClient.get('/owner?view=users'),ApiClient.get('/owner?view=audit-logs'),ApiClient.get('/owner?view=pending-recharges')]);final s=ApiClient.decode(results[0]) as Map;final u=ApiClient.decode(results[1]) as Map;final l=ApiClient.decode(results[2]) as Map;final p=ApiClient.decode(results[3]) as Map;setState(() { stats=Map<String,dynamic>.from(s['metrics']??{}); users=((u['users'] as List?)??const[]).map((e)=>Map<String,dynamic>.from(e)).toList(); logs=((l['logs'] as List?)??const[]).map((e)=>Map<String,dynamic>.from(e)).toList(); pending=((p['requests'] as List?)??const[]).map((e)=>Map<String,dynamic>.from(e)).toList(); error=null; });}catch(e){setState(()=>error='$e');}finally{if(mounted)setState(()=>loading=false);}}
Future<void> resolve(String id,bool approve)async{try{await ApiClient.post('/owner',{'action':approve?'approve':'reject','requestId':id});await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}
Future<void> adjust(String userId)async{final amount=TextEditingController();final reason=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Ajustar créditos'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:amount,keyboardType:const TextInputType.numberWithOptions(signed:true),decoration:const InputDecoration(labelText:'Cantidad (+/-)')),const SizedBox(height:8),TextField(controller:reason,decoration:const InputDecoration(labelText:'Motivo'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Aplicar'))]));if(ok==true){try{await ApiClient.post('/owner',{'action':'adjust-credits','userId':userId,'amount':int.parse(amount.text.trim()),'reason':reason.text.trim()});await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}amount.dispose();reason.dispose();}
@override void initState(){super.initState();load();}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Consola del Propietario')),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[if(error!=null)Text(error!,style:const TextStyle(color:AppColors.red)),if(loading)const LinearProgressIndicator(),if(stats!=null)Wrap(spacing:10,runSpacing:10,children:['totalUsers','totalProjects','circulatingCredits','historicalSpentCredits','auditLogsLogged','serverUptime'].map((k)=>SizedBox(width:160,child:GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(k,style:const TextStyle(color:AppColors.muted,fontSize:11)),const SizedBox(height:6),Text('${stats![k]??0}',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900,color:AppColors.cyan))])))).toList()),const SizedBox(height:20),const Text('Recargas pendientes',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:8),...pending.map((r)=>Padding(padding:const EdgeInsets.only(bottom:8),child:GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${r['user_email']??''}',style:const TextStyle(fontWeight:FontWeight.w800)),Text('${r['price_label']??''} · ${r['credit_amount']??0} créditos',style:const TextStyle(color:AppColors.muted)),SelectableText('Referencia: ${r['reference_code']??''}'),Row(mainAxisAlignment:MainAxisAlignment.end,children:[TextButton(onPressed:()=>resolve('${r['id']}',false),child:const Text('Rechazar',style:TextStyle(color:AppColors.red))),FilledButton(onPressed:()=>resolve('${r['id']}',true),child:const Text('Confirmar pago'))])] ))),const Text('Usuarios',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:8),...users.map((u)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.person_outline,color:AppColors.cyan),title:Text('${u['email']??''}'),subtitle:Text('Rol: ${u['role']??''} · ID ${u['id']??''}',style:const TextStyle(color:AppColors.muted,fontSize:11)),trailing:TextButton(onPressed:()=>adjust('${u['id']}'),child:Text('${u['balance']??0} · Ajustar')))),const Text('Auditoría',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:8),...logs.take(30).map((l)=>GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${l['action']??''}',style:const TextStyle(color:AppColors.cyan,fontWeight:FontWeight.w800)),Text('${l['actor_email']??''} · ${l['timestamp']??''}',style:const TextStyle(color:AppColors.muted,fontSize:11)),SelectableText('${l['details']??''}')])))])));
}
